export const productData = {
  rows: [
    {
      _id: "2868",
      type: "variation",
      group_id: "4888931270734",
      container_id: "4888931270734",
      title: "digital product 22448",
      brand: "Pure Fix Cycles",
      product_type: "Brake",
      description:
        '<p><em>This is a demonstration store. You can purchase products like this from <a href="https://www.purefixcycles.com" target="_blank">Pure Fix Cycles</a></em></p><p>Our Tektro brakes come as a full, dual-pivot, forged alloy set, which includes a brake, caliper, lever, cable, housing, and brake pads. These brakes also come in two awesome colors: alloy and black.</p>\n<p>All of our standard fixies ship with a front brake but if you want that extra safety in the back, be sure to grab a rear brake as well!</p>\n<meta charset="utf-8">\n<ul class="listtype-bullet listindent1 list-bullet1">\n<li>\n<span class="author-p-121029">Brake reach: </span><span class="author-p-142672">41mm-57mmåÊ</span>\n</li>\n</ul>',
      handle: "rear-brake-kit",
      tags: "Alloy,Black,Brake Parts,Brakes,Essential,Essentials,Parts,Safety Gear",
      template_suffix: "",
      main_image: null,
      published_at: "2020-12-04T05:00:24Z",
      created_at: "2020-12-04T05:00:28Z",
      updated_at: "2021-07-08T11:18:42+0000",
      variant_attributes: ["Position", "Color"],
      variant_title: "Rear / Black",
      position: 1,
      sku: "CEDCOSS22563",
      price: 897,
      compare_at_price: null,
      quantity: 100,
      weight: 0.0992,
      weight_unit: "POUNDS",
      grams: 44.99712,
      barcode: "712392689656",
      inventory_policy: "DENY",
      taxable: true,
      fulfillment_service: "manual",
      variant_image: null,
      Position: "Rear",
      Color: "Black",
      inventory_item_id: "34982021529678",
      inventory_tracked: true,
      requires_shipping: true,
      locations: [
        {
          admin_graphql_api_id:
            "gid://shopify/InventoryLevel/69096505422?inventory_item_id=34982021529678",
          updated_at: "2021-05-22T12:58:11Z",
          available: 100,
          location_id: "35356770382",
          inventory_item_id: "34982021529678",
        },
      ],
      user_id: "60af799b08dd5033b951d415",
      source_product_id: "32768348553294",
      is_imported: 0,
      visibility: "Not Visible Individually",
      app_codes: ["amazon_sales_channel"],
      shop_id: "3",
      source_marketplace: "shopify",
      additional_images: [],
      db_action: "variant_update",
      marketplace: {
        amazon: [
          {
            shop_id: "357",
            process_tags: [],
            seller_id: "A3VSMOL1YWESR0",
            error: [],
          },
        ],
      },
      low_sku: "cedcoss22563",
      price_with_currency: "897 INR",
      amazon_currency: "INR",
      edited_data: {
        container_id: "4888931270734",
        source_product_id: "32768348553294",
        user_id: "60af799b08dd5033b951d415",
        group_id: "4888931270734",
        barcode: "741360638112",
        inventory_fulfillment_latency: "11",
        shops: {
          357: {
            optional_attributes: {
              part_number: "1",
            },
            variation_theme_attribute_name: "Color",
            variation_theme_attribute_value: {
              color_name: "r",
              color_map: "Bronze",
            },
            category_settings: {
              primary_category: "biss_mechanical_fasteners",
              sub_category: "screws",
              browser_node_id: "1380209031",
              barcode_exemption: true,
              attributes_mapping: {
                required_attribute: [
                  {
                    amazon_attribute: "brand_name",
                    shopify_attribute: "tags",
                    recommendation: "",
                    custom_text: "",
                    shopify_select: "Search",
                  },
                  {
                    amazon_attribute: "manufacturer",
                    shopify_attribute: "price",
                    recommendation: "",
                    custom_text: "",
                    shopify_select: "Search",
                  },
                  {
                    amazon_attribute: "part_number",
                    shopify_attribute: "quantity",
                    recommendation: "",
                    custom_text: "",
                    shopify_select: "Search",
                  },
                  {
                    amazon_attribute: "product_description",
                    shopify_attribute: "brand",
                    recommendation: "",
                    custom_text: "",
                    shopify_select: "Search",
                  },
                  {
                    amazon_attribute: "material_type1",
                    shopify_attribute: "",
                    recommendation: "Aflas rubber",
                    custom_text: "",
                    shopify_select: "recommendation",
                  },
                  {
                    amazon_attribute: "country_of_origin",
                    shopify_attribute: "weight",
                    recommendation: "",
                    custom_text: "",
                    shopify_select: "Search",
                  },
                  {
                    amazon_attribute: "external_product_information",
                    shopify_attribute: "quantity",
                    recommendation: "",
                    custom_text: "",
                    shopify_select: "Search",
                  },
                  {
                    amazon_attribute: "number_of_items",
                    shopify_attribute: "quantity",
                    recommendation: "",
                    custom_text: "",
                    shopify_select: "Search",
                  },
                  {
                    amazon_attribute: "maximum_retail_price",
                    shopify_attribute: "price",
                    recommendation: "",
                    custom_text: "",
                    shopify_select: "Search",
                  },
                ],
                optional_attribute: [],
              },
            },
          },
        },
        sku: "CEDCOSS22563",
        price: 39,
        quantity: 100,
        profile_data: {
          inventory: {
            settings_enabled: true,
            settings_selected: {
              fixed_inventory: false,
              threshold_inventory: false,
              delete_out_of_stock: false,
              customize_inventory: true,
              inventory_fulfillment_latency: true,
              warehouses_settings: false,
            },
            fixed_inventory: "",
            threshold_inventory: "",
            customize_inventory: {
              attribute: "default",
              value: "100",
            },
            warehouses_settings: ["60898869326", "35356770382"],
            inventory_fulfillment_latency: "2",
          },
          pricing: {
            settings_enabled: true,
            settings_selected: {
              sale_price: false,
              business_price: false,
              minimum_price: false,
            },
            standard_price: {
              attribute: "default",
              value: "default",
            },
            sale_price: {
              attribute: "default",
              value: "",
              start_date: "",
              end_date: "",
            },
            business_price: {
              attribute: "default",
              value: "",
            },
            minimum_price: {
              attribute: "default",
              value: "default",
            },
          },
          profile_id: "default",
          profile_name: "default",
        },
        profile_id: "default",
        profile_name: "default",
      },
    },
    {
      _id: "2867",
      user_id: "60af799b08dd5033b951d415",
      source_product_id: "4888931270734",
      container_id: "4888931270734",
      title: "digital product 22448",
      vendor: "Aerospoke",
      product_type: "Apparel",
      tags: "700C, 700C Wheelsets, Aerospoke, Black, Red, Wheel, Wheelset, Wheelsets and Accessories, White",
      description:
        '<p><em>This is a demonstration store. You can purchase products like this from <a href="https://www.purefixcycles.com" target="_blank">Pure Fix Cycles</a></em></p><p>Our Tektro brakes come as a full, dual-pivot, forged alloy set, which includes a brake, caliper, lever, cable, housing, and brake pads. These brakes also come in two awesome colors: alloy and black.</p>\n<p>All of our standard fixies ship with a front brake but if you want that extra safety in the back, be sure to grab a rear brake as well!</p>\n<meta charset="utf-8">\n<ul class="listtype-bullet listindent1 list-bullet1">\n<li>\n<span class="author-p-121029">Brake reach: </span><span class="author-p-142672">41mm-57mmåÊ</span>\n</li>\n</ul>',
      type: "variation",
      brand: "Pure Fix Cycles",
      product_type: "Brake",
      additional_images: [],
      is_imported: 0,
      visibility: "Catalog and Search",
      variant_attributes: ["Position", "Color"],
      app_codes: ["amazon_sales_channel"],
      shop_id: "3",
      created_at: "2021-06-02 12:45:34",
      source_marketplace: "shopify",
      marketplace: {
        amazon: [
          {
            shop_id: "357",
            process_tags: [],
            seller_id: "A3VSMOL1YWESR0",
            error: [],
          },
        ],
      },
      ebay_product_data: {
        _id: {
          $oid: "619761eb0bbb5ba16993116d",
        },
        ItemID: "110540828207",
        user_id: "694",
        AutoPay: true,
        BuyItNowPrice: {
          value: 0,
          currencyID: "USD",
        },
        BuyerGuaranteePrice: {
          value: 20000,
          currencyID: "USD",
        },
        BuyerProtection: "ItemIneligible",
        BuyerResponsibleForShipping: false,
        ConditionDisplayName: "New – Open box",
        ConditionID: 1500,
        Country: "KR",
        Currency: "USD",
        Description: "fgrfebvgbb",
        DispatchTimeMax: 1,
        HideFromSearch: false,
        HitCount: 0,
        HitCounter: "NoHitCounter",
        IsSecureDescription: true,
        ItemSpecifics: {
          NameValueList: [
            {
              Name: "Brand",
              Value: ["dev-quallity-assurance"],
              Source: "ItemSpecific",
            },
            {
              Name: "MPN",
              Value: ["White_1"],
              Source: "ItemSpecific",
            },
          ],
        },
        ListingDesigner: {
          LayoutID: 10000,
          ThemeID: 10,
        },
        ListingDetails: {
          Adult: false,
          BindingAuction: false,
          CheckoutEnabled: true,
          ConvertedBuyItNowPrice: {
            value: 0,
            currencyID: "USD",
          },
          ConvertedStartPrice: {
            value: 5,
            currencyID: "USD",
          },
          ConvertedReservePrice: {
            value: 0,
            currencyID: "USD",
          },
          HasReservePrice: false,
          StartTime: "2021-11-19T08:35:53.000Z",
          EndTime: "2021-12-19T08:35:53.000Z",
          ViewItemURL:
            "https://www.sandbox.ebay.com/itm/ACS-Crossfire-Chain-02-test-/110540828207",
          HasUnansweredQuestions: false,
          HasPublicMessages: false,
          ViewItemURLForNaturalSearch:
            "https://www.sandbox.ebay.com/itm/ACS-Crossfire-Chain-02-test-/110540828207",
        },
        ListingDuration: "GTC",
        ListingType: "FixedPriceItem",
        Location: "KR",
        LocationDefaulted: true,
        PayPalEmailAddress: "admin@admin.com",
        PaymentAllowedSite: ["Canada", "CanadaFrench", "eBayMotors", "US"],
        PaymentMethods: ["PayPal"],
        PictureDetails: {
          GalleryURL:
            "https://cdn.shopify.com/s/files/1/0267/1443/9758/products/elegant.jpg?v=1584709400",
          GalleryType: "Gallery",
          PhotoDisplay: "None",
          PictureURL: [
            "https://cdn.shopify.com/s/files/1/0267/1443/9758/products/elegant.jpg?v=1584709400",
          ],
          PictureSource: "Vendor",
          ExternalPictureURL: [
            "https://cdn.shopify.com/s/files/1/0267/1443/9758/products/elegant.jpg?v=1584709400",
          ],
        },
        PostalCode: "99501",
        PrimaryCategory: {
          CategoryID: "183903",
          CategoryName:
            "Business & Industrial:Facility Maintenance & Safety:Safety Signs & Traffic Control:Speed Bumps",
        },
        ProductListingDetails: {
          BrandMPN: {
            Brand: "dev-quallity-assurance",
            MPN: "White_1",
          },
          IncludeeBayProductDetails: true,
        },
        ProxyItem: false,
        Quantity: 30,
        ReservePrice: {
          value: 0,
          currencyID: "USD",
        },
        ReturnPolicy: {
          RefundOption: "MoneyBack",
          Refund: "Money Back",
          ReturnsWithinOption: "Days_30",
          ReturnsWithin: "30 Days",
          ReturnsAcceptedOption: "ReturnsAccepted",
          ReturnsAccepted: "Returns Accepted",
          ShippingCostPaidByOption: "Buyer",
          ShippingCostPaidBy: "Buyer",
        },
        ReviseStatus: {
          ItemRevised: true,
        },
        Seller: {
          AboutMePage: false,
          Email: "pankajaswal@hotmail.com",
          FeedbackScore: 1,
          PositiveFeedbackPercent: 75,
          FeedbackPrivate: false,
          IDVerified: false,
          eBayGoodStanding: true,
          NewUser: false,
          RegistrationDate: "2006-01-01T00:00:00.000Z",
          Site: "US",
          Status: "Confirmed",
          UserID: "testuser_pankaj9839",
          UserIDChanged: false,
          UserIDLastChanged: "2016-11-25T07:36:20.000Z",
          VATStatus: "NoVATTax",
          SellerInfo: {
            AllowPaymentEdit: true,
            CheckoutEnabled: true,
            CIPBankAccountStored: false,
            GoodStanding: true,
            QualifiesForB2BVAT: false,
            StoreOwner: false,
            SafePaymentExempt: true,
          },
          MotorsDealer: false,
        },
        SellerProfiles: {
          SellerShippingProfile: {
            ShippingProfileID: 6074077000,
            ShippingProfileName: "sanover",
          },
          SellerReturnProfile: {
            ReturnProfileID: 5710216000,
            ReturnProfileName: "Returns Accepted,Buyer,30 Days,Money Back#0",
          },
          SellerPaymentProfile: {
            PaymentProfileID: 6075866000,
            PaymentProfileName: "Test Payment profile test",
          },
        },
        SellingStatus: {
          BidCount: 0,
          BidIncrement: {
            value: 0,
            currencyID: "USD",
          },
          ConvertedCurrentPrice: {
            value: 5,
            currencyID: "USD",
          },
          CurrentPrice: {
            value: 5,
            currencyID: "USD",
          },
          LeadCount: 0,
          MinimumToBid: {
            value: 5,
            currencyID: "USD",
          },
          QuantitySold: 0,
          ReserveMet: true,
          SecondChanceEligible: false,
          ListingStatus: "Active",
          QuantitySoldByPickupInStore: 0,
        },
        ShipToLocations: ["US"],
        ShippingDetails: {
          CalculatedShippingRate: [],
          PaymentInstructions: "This is perfect for you",
          SalesTax: {
            SalesTaxPercent: 0,
            ShippingIncludedInTax: false,
          },
          ShippingServiceOptions: [
            {
              ShippingService: "USPSFirstClass",
              ShippingServiceCost: {
                value: 0,
                currencyID: "USD",
              },
              ShippingServiceAdditionalCost: {
                value: 0,
                currencyID: "USD",
              },
              ShippingServicePriority: 1,
              ExpeditedService: false,
              ShippingTimeMin: 3,
              ShippingTimeMax: 5,
              FreeShipping: true,
            },
          ],
          ShippingType: "Flat",
          ShippingDiscountProfileID: "0",
          InternationalShippingDiscountProfileID: "0",
          SellerExcludeShipToLocationsPreference: true,
        },
        ShippingPackageDetails: {
          ShippingIrregular: false,
          ShippingPackage: "None",
          WeightMajor: {
            value: 0,
            unit: "lbs",
            measurementSystem: "English",
          },
          WeightMinor: {
            value: 0,
            unit: "oz",
            measurementSystem: "English",
          },
        },
        Site: "US",
        StartPrice: {
          value: 5,
          currencyID: "USD",
        },
        TimeLeft: "PT0S",
        Title: "ACS Crossfire Chain 02 test",
        Variations: {
          Variation: [
            {
              SKU: "White_1",
              StartPrice: {
                value: 5,
                currencyID: "USD",
              },
              Quantity: 10,
              VariationSpecifics: [
                {
                  NameValueList: [
                    {
                      Name: "Size",
                      Value: ["medium"],
                    },
                  ],
                },
              ],
              SellingStatus: {
                QuantitySold: 0,
                QuantitySoldByPickupInStore: 0,
              },
            },
            {
              SKU: "White_2",
              StartPrice: {
                value: 15,
                currencyID: "USD",
              },
              Quantity: 20,
              VariationSpecifics: [
                {
                  NameValueList: [
                    {
                      Name: "Size",
                      Value: ["small"],
                    },
                  ],
                },
              ],
              SellingStatus: {
                QuantitySold: 0,
                QuantitySoldByPickupInStore: 0,
              },
            },
          ],
          VariationSpecificsSet: {
            NameValueList: [
              {
                Name: "Size",
                Value: ["medium", "small"],
              },
            ],
          },
        },
        WatchCount: 0,
        eBayPlus: false,
        eBayPlusEligible: false,
      },
      details: {
        product_dimensions: {
          length: 123,
          width: 123,
          height: 123,
          unit: "in",
        },
        source_product_id: "4591819128910",
        title: "ACS Crossfire Chain 02 test123",
        short_description: "<p>fgrfebvgbb123</p>\n",
        long_description: "<p>fgrfebvgbb123</p>\n",
        type: "variant",
        attribute_set: "",
        vendor: "dev-quallity-assurance123",
        handle: "acs-crossfire-chain-02",
        product_type: "123",
        image_array: [
          {
            product_id: 4591819128910,
            id: 14377039396942,
            position: 1,
            created_at: "2020-03-20T09:03:20-04:00",
            updated_at: "2020-03-20T09:03:20-04:00",
            alt: null,
            width: 224,
            height: 225,
            src: "https://cdn.shopify.com/s/files/1/0267/1443/9758/products/elegant.jpg?v=1584709400",
            variant_ids: [],
            admin_graphql_api_id: "gid://shopify/ProductImage/14377039396942",
          },
        ],
        image_main:
          "https://cdn.shopify.com/s/files/1/0267/1443/9758/products/elegant.jpg?v=1584709400",
        tags: "123",
      },
      status: "Error",
      report: [
        {
          ShortMessage: "Best offer feature disabled.",
          LongMessage:
            "Best offer feature is unavailable or disabled for the specified category or listing type.",
          ErrorCode: "20135",
          SeverityCode: "Warning",
          ErrorClassification: "RequestError",
        },
        {
          ShortMessage:
            "The ConditionDescription field is not valid for new items.",
          LongMessage:
            "The ConditionDescription field is not valid for new items. The data specified in the field will be ignored.",
          ErrorCode: "21919111",
          SeverityCode: "Warning",
          ErrorClassification: "RequestError",
        },
        {
          ShortMessage: "Category 16080 requires custom item specifics.",
          LongMessage: "Category 16080 requires custom item specifics.",
          ErrorCode: "21916516",
          SeverityCode: "Warning",
          ErrorParameters: [
            {
              Value: "16080",
              ParamID: "0",
            },
          ],
          ErrorClassification: "RequestError",
        },
        {
          ShortMessage: "Variation Specifics Mismatch.",
          LongMessage:
            "Variation Specifics provided does not match with the variation specifics of the variations on the item.",
          ErrorCode: "21916664",
          SeverityCode: "Error",
          ErrorClassification: "RequestError",
        },
      ],
      low_sku: "",
      edited_data: {
        container_id: "4888931270734",
        source_product_id: "4888931270734",
        user_id: "60af799b08dd5033b951d415",
        parent_sku: "4888931270734",
        shops: {
          357: {
            variation_theme_attribute_name: "Color",
            category_settings: {
              primary_category: "biss_mechanical_fasteners",
              sub_category: "screws",
              browser_node_id: "1380209031",
              barcode_exemption: true,
            },
          },
        },
        profile_data: {
          inventory: {
            settings_enabled: true,
            settings_selected: {
              fixed_inventory: false,
              threshold_inventory: false,
              delete_out_of_stock: false,
              customize_inventory: true,
              inventory_fulfillment_latency: true,
              warehouses_settings: false,
            },
            fixed_inventory: "",
            threshold_inventory: "",
            customize_inventory: {
              attribute: "default",
              value: "100",
            },
            warehouses_settings: ["60898869326", "35356770382"],
            inventory_fulfillment_latency: "2",
          },
          pricing: {
            settings_enabled: true,
            settings_selected: {
              sale_price: false,
              business_price: false,
              minimum_price: false,
            },
            standard_price: {
              attribute: "default",
              value: "default",
            },
            sale_price: {
              attribute: "default",
              value: "",
              start_date: "",
              end_date: "",
            },
            business_price: {
              attribute: "default",
              value: "",
            },
            minimum_price: {
              attribute: "default",
              value: "default",
            },
          },
          profile_id: "default",
          profile_name: "default",
        },
        profile_id: "default",
        profile_name: "default",
      },
      image_array: [
        {
          id: 14166079144014,
          product_id: 4546948497486,
          position: 1,
          created_at: "2020-02-06T05:21:24-05:00",
          updated_at: "2020-02-06T05:21:24-05:00",
          alt: null,
          width: 1920,
          height: 1280,
          src: "https://cdn.shopify.com/s/files/1/0267/1443/9758/products/ArtBike_people-for-bikes-3_WEB.jpg?v=1580984484",
          variant_ids: [],
          admin_graphql_api_id: "gid://shopify/ProductImage/14166079144014",
        },
        {
          id: 14166079176782,
          product_id: 4546948497486,
          position: 2,
          created_at: "2020-02-06T05:21:24-05:00",
          updated_at: "2020-02-06T05:21:24-05:00",
          alt: null,
          width: 2048,
          height: 1365,
          src: "https://cdn.shopify.com/s/files/1/0267/1443/9758/products/peter-shire-bike-side.jpg?v=1580984484",
          variant_ids: [],
          admin_graphql_api_id: "gid://shopify/ProductImage/14166079176782",
        },
        {
          id: 14166079209550,
          product_id: 4546948497486,
          position: 3,
          created_at: "2020-02-06T05:21:24-05:00",
          updated_at: "2020-02-06T05:21:24-05:00",
          alt: null,
          width: 2048,
          height: 1365,
          src: "https://cdn.shopify.com/s/files/1/0267/1443/9758/products/peter-shire-bike.jpg?v=1580984484",
          variant_ids: [],
          admin_graphql_api_id: "gid://shopify/ProductImage/14166079209550",
        },
        {
          id: 14166079242318,
          product_id: 4546948497486,
          position: 4,
          created_at: "2020-02-06T05:21:24-05:00",
          updated_at: "2020-02-06T05:21:24-05:00",
          alt: null,
          width: 2048,
          height: 1365,
          src: "https://cdn.shopify.com/s/files/1/0267/1443/9758/products/peter-shire-sign.jpg?v=1580984484",
          variant_ids: [],
          admin_graphql_api_id: "gid://shopify/ProductImage/14166079242318",
        },
        {
          id: 14166079275086,
          product_id: 4546948497486,
          position: 5,
          created_at: "2020-02-06T05:21:24-05:00",
          updated_at: "2020-02-06T05:21:24-05:00",
          alt: null,
          width: 2048,
          height: 1365,
          src: "https://cdn.shopify.com/s/files/1/0267/1443/9758/products/peter-shire-art.jpg?v=1580984484",
          variant_ids: [],
          admin_graphql_api_id: "gid://shopify/ProductImage/14166079275086",
        },
        {
          id: 14166079307854,
          product_id: 4546948497486,
          position: 6,
          created_at: "2020-02-06T05:21:24-05:00",
          updated_at: "2020-02-06T05:21:24-05:00",
          alt: null,
          width: 2048,
          height: 1365,
          src: "https://cdn.shopify.com/s/files/1/0267/1443/9758/products/peter-shire-espresso.jpg?v=1580984484",
          variant_ids: [],
          admin_graphql_api_id: "gid://shopify/ProductImage/14166079307854",
        },
        {
          id: 14166079340622,
          product_id: 4546948497486,
          position: 7,
          created_at: "2020-02-06T05:21:24-05:00",
          updated_at: "2020-02-06T05:21:24-05:00",
          alt: null,
          width: 2048,
          height: 1365,
          src: "https://cdn.shopify.com/s/files/1/0267/1443/9758/products/peter-shire-workshop.jpg?v=1580984484",
          variant_ids: [],
          admin_graphql_api_id: "gid://shopify/ProductImage/14166079340622",
        },
        {
          id: 14166079176782,
          product_id: 4546948497486,
          position: 2,
          created_at: "2020-02-06T05:21:24-05:00",
          updated_at: "2020-02-06T05:21:24-05:00",
          alt: null,
          width: 2048,
          height: 1365,
          src: "https://cdn.shopify.com/s/files/1/0267/1443/9758/products/peter-shire-bike-side.jpg?v=1580984484",
          variant_ids: [],
          admin_graphql_api_id: "gid://shopify/ProductImage/14166079176782",
        },
        {
          id: 14166079209550,
          product_id: 4546948497486,
          position: 3,
          created_at: "2020-02-06T05:21:24-05:00",
          updated_at: "2020-02-06T05:21:24-05:00",
          alt: null,
          width: 2048,
          height: 1365,
          src: "https://cdn.shopify.com/s/files/1/0267/1443/9758/products/peter-shire-bike.jpg?v=1580984484",
          variant_ids: [],
          admin_graphql_api_id: "gid://shopify/ProductImage/14166079209550",
        },
        {
          id: 14166079242318,
          product_id: 4546948497486,
          position: 4,
          created_at: "2020-02-06T05:21:24-05:00",
          updated_at: "2020-02-06T05:21:24-05:00",
          alt: null,
          width: 2048,
          height: 1365,
          src: "https://cdn.shopify.com/s/files/1/0267/1443/9758/products/peter-shire-sign.jpg?v=1580984484",
          variant_ids: [],
          admin_graphql_api_id: "gid://shopify/ProductImage/14166079242318",
        },
        {
          id: 14166079275086,
          product_id: 4546948497486,
          position: 5,
          created_at: "2020-02-06T05:21:24-05:00",
          updated_at: "2020-02-06T05:21:24-05:00",
          alt: null,
          width: 2048,
          height: 1365,
          src: "https://cdn.shopify.com/s/files/1/0267/1443/9758/products/peter-shire-art.jpg?v=1580984484",
          variant_ids: [],
          admin_graphql_api_id: "gid://shopify/ProductImage/14166079275086",
        },
        {
          id: 14166079307854,
          product_id: 4546948497486,
          position: 6,
          created_at: "2020-02-06T05:21:24-05:00",
          updated_at: "2020-02-06T05:21:24-05:00",
          alt: null,
          width: 2048,
          height: 1365,
          src: "https://cdn.shopify.com/s/files/1/0267/1443/9758/products/peter-shire-espresso.jpg?v=1580984484",
          variant_ids: [],
          admin_graphql_api_id: "gid://shopify/ProductImage/14166079307854",
        },
      ],
      image_main:
        "https://cdn.shopify.com/s/files/1/0267/1443/9758/products/ArtBike_people-for-bikes-3_WEB.jpg?v=1580984484",
    },
    {
      _id: "2869",
      type: "variation",
      group_id: "4888931270734",
      container_id: "4888931270734",
      title: "digital product 22448",
      brand: "Pure Fix Cycles",
      product_type: "Brake",
      description:
        '<p><em>This is a demonstration store. You can purchase products like this from <a href="https://www.purefixcycles.com" target="_blank">Pure Fix Cycles</a></em></p><p>Our Tektro brakes come as a full, dual-pivot, forged alloy set, which includes a brake, caliper, lever, cable, housing, and brake pads. These brakes also come in two awesome colors: alloy and black.</p>\n<p>All of our standard fixies ship with a front brake but if you want that extra safety in the back, be sure to grab a rear brake as well!</p>\n<meta charset="utf-8">\n<ul class="listtype-bullet listindent1 list-bullet1">\n<li>\n<span class="author-p-121029">Brake reach: </span><span class="author-p-142672">41mm-57mmåÊ</span>\n</li>\n</ul>',
      handle: "rear-brake-kit",
      tags: "Alloy,Black,Brake Parts,Brakes,Essential,Essentials,Parts,Safety Gear",
      template_suffix: "",
      main_image: null,
      published_at: "2020-12-04T05:00:24Z",
      created_at: "2020-12-04T05:00:28Z",
      updated_at: "2021-07-08T11:18:43+0000",
      variant_attributes: ["Position", "Color"],
      variant_title: "Rear / Alloy",
      position: 2,
      sku: "CEDCOSS22564",
      price: 897,
      compare_at_price: null,
      quantity: 200,
      weight: 0.0992,
      weight_unit: "POUNDS",
      grams: 44.99712,
      barcode: "741360638112",
      inventory_policy: "DENY",
      taxable: true,
      fulfillment_service: "manual",
      variant_image: null,
      Position: "Rear",
      Color: "Alloy",
      inventory_item_id: "34982021562446",
      inventory_tracked: true,
      requires_shipping: true,
      locations: [
        {
          admin_graphql_api_id:
            "gid://shopify/InventoryLevel/69096505422?inventory_item_id=34982021562446",
          updated_at: "2021-05-22T13:06:36Z",
          available: 200,
          location_id: "35356770382",
          inventory_item_id: "34982021562446",
        },
      ],
      user_id: "60af799b08dd5033b951d415",
      source_product_id: "32768348586062",
      is_imported: 0,
      visibility: "Not Visible Individually",
      app_codes: ["amazon_sales_channel"],
      shop_id: "3",
      source_marketplace: "shopify",
      additional_images: [],
      db_action: "variant_update",
      marketplace: {
        amazon: [
          {
            shop_id: "357",
            process_tags: ["Image sync in progress"],
            seller_id: "A3VSMOL1YWESR0",
            error: [],
          },
        ],
      },
      low_sku: "cedcoss22564",
      price_with_currency: "897 INR",
      amazon_currency: "INR",
      edited_data: {
        container_id: "4888931270734",
        source_product_id: "32768348586062",
        user_id: "60af799b08dd5033b951d415",
        group_id: "4888931270734",
        barcode: "",
        inventory_fulfillment_latency: "11",
        shops: {
          357: {
            optional_attributes: {
              part_number: "1",
            },
            variation_theme_attribute_name: "Color",
            variation_theme_attribute_value: {
              color_name: "r",
              color_map: "Bronze",
            },
            category_settings: {
              primary_category: "biss_mechanical_fasteners",
              sub_category: "screws",
              browser_node_id: "1380209031",
              barcode_exemption: true,
              attributes_mapping: {
                required_attribute: [
                  {
                    amazon_attribute: "brand_name",
                    shopify_attribute: "tags",
                    recommendation: "",
                    custom_text: "",
                    shopify_select: "Search",
                  },
                  {
                    amazon_attribute: "manufacturer",
                    shopify_attribute: "price",
                    recommendation: "",
                    custom_text: "",
                    shopify_select: "Search",
                  },
                  {
                    amazon_attribute: "part_number",
                    shopify_attribute: "quantity",
                    recommendation: "",
                    custom_text: "",
                    shopify_select: "Search",
                  },
                  {
                    amazon_attribute: "product_description",
                    shopify_attribute: "brand",
                    recommendation: "",
                    custom_text: "",
                    shopify_select: "Search",
                  },
                  {
                    amazon_attribute: "material_type1",
                    shopify_attribute: "",
                    recommendation: "Aflas rubber",
                    custom_text: "",
                    shopify_select: "recommendation",
                  },
                  {
                    amazon_attribute: "country_of_origin",
                    shopify_attribute: "weight",
                    recommendation: "",
                    custom_text: "",
                    shopify_select: "Search",
                  },
                  {
                    amazon_attribute: "external_product_information",
                    shopify_attribute: "quantity",
                    recommendation: "",
                    custom_text: "",
                    shopify_select: "Search",
                  },
                  {
                    amazon_attribute: "number_of_items",
                    shopify_attribute: "quantity",
                    recommendation: "",
                    custom_text: "",
                    shopify_select: "Search",
                  },
                  {
                    amazon_attribute: "maximum_retail_price",
                    shopify_attribute: "price",
                    recommendation: "",
                    custom_text: "",
                    shopify_select: "Search",
                  },
                ],
                optional_attribute: [],
              },
            },
          },
        },
        sku: "CEDCOSS22564",
        price: 39,
        quantity: 200,
        profile_data: {
          inventory: {
            settings_enabled: true,
            settings_selected: {
              fixed_inventory: false,
              threshold_inventory: false,
              delete_out_of_stock: false,
              customize_inventory: true,
              inventory_fulfillment_latency: true,
              warehouses_settings: false,
            },
            fixed_inventory: "",
            threshold_inventory: "",
            customize_inventory: {
              attribute: "default",
              value: "100",
            },
            warehouses_settings: ["60898869326", "35356770382"],
            inventory_fulfillment_latency: "2",
          },
          pricing: {
            settings_enabled: true,
            settings_selected: {
              sale_price: false,
              business_price: false,
              minimum_price: false,
            },
            standard_price: {
              attribute: "default",
              value: "default",
            },
            sale_price: {
              attribute: "default",
              value: "",
              start_date: "",
              end_date: "",
            },
            business_price: {
              attribute: "default",
              value: "",
            },
            minimum_price: {
              attribute: "default",
              value: "default",
            },
          },
          profile_id: "default",
          profile_name: "default",
        },
        profile_id: "default",
        profile_name: "default",
      },
    },
    {
      _id: "2870",
      type: "variation",
      group_id: "4888931270734",
      container_id: "4888931270734",
      title: "digital product 22448",
      brand: "Pure Fix Cycles",
      product_type: "Brake",
      description:
        '<p><em>This is a demonstration store. You can purchase products like this from <a href="https://www.purefixcycles.com" target="_blank">Pure Fix Cycles</a></em></p><p>Our Tektro brakes come as a full, dual-pivot, forged alloy set, which includes a brake, caliper, lever, cable, housing, and brake pads. These brakes also come in two awesome colors: alloy and black.</p>\n<p>All of our standard fixies ship with a front brake but if you want that extra safety in the back, be sure to grab a rear brake as well!</p>\n<meta charset="utf-8">\n<ul class="listtype-bullet listindent1 list-bullet1">\n<li>\n<span class="author-p-121029">Brake reach: </span><span class="author-p-142672">41mm-57mmåÊ</span>\n</li>\n</ul>',
      handle: "rear-brake-kit",
      tags: "Alloy,Black,Brake Parts,Brakes,Essential,Essentials,Parts,Safety Gear",
      template_suffix: "",
      main_image: null,
      published_at: "2020-12-04T05:00:24Z",
      created_at: "2020-12-04T05:00:28Z",
      updated_at: "2021-07-08T11:18:43+0000",
      variant_attributes: ["Position", "Color"],
      variant_title: "Front / Black",
      position: 3,
      sku: "CEDCOSS22565",
      price: 897,
      compare_at_price: null,
      quantity: 10,
      weight: 0.0992,
      weight_unit: "POUNDS",
      grams: 44.99712,
      barcode: "712392689632",
      inventory_policy: "DENY",
      taxable: true,
      fulfillment_service: "manual",
      variant_image: null,
      Position: "Front",
      Color: "Black",
      inventory_item_id: "34982021595214",
      inventory_tracked: true,
      requires_shipping: true,
      locations: [
        {
          admin_graphql_api_id:
            "gid://shopify/InventoryLevel/69096505422?inventory_item_id=34982021595214",
          updated_at: "2021-05-22T11:14:22Z",
          available: 10,
          location_id: "35356770382",
          inventory_item_id: "34982021595214",
        },
      ],
      user_id: "60af799b08dd5033b951d415",
      source_product_id: "32768348618830",
      is_imported: 0,
      visibility: "Not Visible Individually",
      app_codes: ["amazon_sales_channel"],
      shop_id: "3",
      source_marketplace: "shopify",
      additional_images: [],
      db_action: "variant_update",
      marketplace: {
        amazon: [
          {
            shop_id: "357",
            process_tags: ["Image sync in progress"],
            seller_id: "A3VSMOL1YWESR0",
            error: [],
          },
        ],
      },
      low_sku: "cedcoss22565",
      price_with_currency: "897 INR",
      amazon_currency: "INR",
      edited_data: {
        container_id: "4888931270734",
        source_product_id: "32768348618830",
        user_id: "60af799b08dd5033b951d415",
        group_id: "4888931270734",
        barcode: "712392689632",
        inventory_fulfillment_latency: "11",
        shops: {
          357: {
            optional_attributes: {
              part_number: "1",
            },
            variation_theme_attribute_name: "Color",
            variation_theme_attribute_value: {
              color_name: "r",
              color_map: "Copper",
            },
            category_settings: {
              primary_category: "biss_mechanical_fasteners",
              sub_category: "screws",
              browser_node_id: "1380209031",
              barcode_exemption: true,
              attributes_mapping: {
                required_attribute: [
                  {
                    amazon_attribute: "brand_name",
                    shopify_attribute: "tags",
                    recommendation: "",
                    custom_text: "",
                    shopify_select: "Search",
                  },
                  {
                    amazon_attribute: "manufacturer",
                    shopify_attribute: "price",
                    recommendation: "",
                    custom_text: "",
                    shopify_select: "Search",
                  },
                  {
                    amazon_attribute: "part_number",
                    shopify_attribute: "quantity",
                    recommendation: "",
                    custom_text: "",
                    shopify_select: "Search",
                  },
                  {
                    amazon_attribute: "product_description",
                    shopify_attribute: "brand",
                    recommendation: "",
                    custom_text: "",
                    shopify_select: "Search",
                  },
                  {
                    amazon_attribute: "material_type1",
                    shopify_attribute: "",
                    recommendation: "Aflas rubber",
                    custom_text: "",
                    shopify_select: "recommendation",
                  },
                  {
                    amazon_attribute: "country_of_origin",
                    shopify_attribute: "weight",
                    recommendation: "",
                    custom_text: "",
                    shopify_select: "Search",
                  },
                  {
                    amazon_attribute: "external_product_information",
                    shopify_attribute: "quantity",
                    recommendation: "",
                    custom_text: "",
                    shopify_select: "Search",
                  },
                  {
                    amazon_attribute: "number_of_items",
                    shopify_attribute: "quantity",
                    recommendation: "",
                    custom_text: "",
                    shopify_select: "Search",
                  },
                  {
                    amazon_attribute: "maximum_retail_price",
                    shopify_attribute: "price",
                    recommendation: "",
                    custom_text: "",
                    shopify_select: "Search",
                  },
                ],
                optional_attribute: [],
              },
            },
          },
        },
        sku: "CEDCOSS22565",
        price: 39,
        quantity: 10,
        profile_data: {
          inventory: {
            settings_enabled: true,
            settings_selected: {
              fixed_inventory: false,
              threshold_inventory: false,
              delete_out_of_stock: false,
              customize_inventory: true,
              inventory_fulfillment_latency: true,
              warehouses_settings: false,
            },
            fixed_inventory: "",
            threshold_inventory: "",
            customize_inventory: {
              attribute: "default",
              value: "100",
            },
            warehouses_settings: ["60898869326", "35356770382"],
            inventory_fulfillment_latency: "2",
          },
          pricing: {
            settings_enabled: true,
            settings_selected: {
              sale_price: false,
              business_price: false,
              minimum_price: false,
            },
            standard_price: {
              attribute: "default",
              value: "default",
            },
            sale_price: {
              attribute: "default",
              value: "",
              start_date: "",
              end_date: "",
            },
            business_price: {
              attribute: "default",
              value: "",
            },
            minimum_price: {
              attribute: "default",
              value: "default",
            },
          },
          profile_id: "default",
          profile_name: "default",
        },
        profile_id: "default",
        profile_name: "default",
      },
    },
  ],
};
